#!/bin/sh

set -o noclobber  # Avoid overlay files (echo "hi" > foo)
set -o errexit    # Used to exit upon error, avoiding cascading errors
set -o pipefail   # Unveils hidden failures
set -o nounset    # Exposes unset variables
set -o errtrace   # Trace error LINENO

trap 'echo Error at $LINENO' ERR

MIN_HUE_DISTANCE=80

MX_CC=( UNO DOS C{00..15} )

mkdir out 2> /dev/null || true

logv () {
  while [ "$1" ]; do
    echo "${1} ${!1}"
    shift
  done
}

generate_seed () {
  diff_real () { echo "df=($1 - $2); if (df < 0) { df=df* -1}; print df" | bc -l; }
  local strategy=${STRATEGY:-vivid}
  declare -g UNO="$(pastel random -n 1 -s "$strategy" | pastel format hex)"
  declare -g DOS="$(pastel random -n 1 -s "$strategy" | pastel format hex)"

  local uno_hue; uno_hue="$(pastel format hsl-hue "$UNO")"
  local dos_hue; dos_hue="$(pastel format hsl-hue "$DOS")"
  local diff; diff=$(diff_real "$uno_hue" "$dos_hue")

  (( $(echo "$diff < $MIN_HUE_DISTANCE" | bc -l) )) &&  generate_seed "${@}" || true
}

generate_palette () {
  C00="$(pastel set hsl-saturation 0.08 "${UNO}" | pastel set hsl-lightness 0.1 | pastel lighten 0.02 | pastel format hex)"
  C08="$(pastel set hsl-saturation 0.08 "${UNO}" | pastel set hsl-lightness 0.2 | pastel lighten 0.08 | pastel format hex)"
  C07="$(pastel set hsl-saturation 0.08 "${UNO}" | pastel set hsl-lightness 0.3 | pastel lighten 0.16 | pastel format hex)"
  C15="$(pastel set hsl-saturation 0.08 "${UNO}" | pastel set hsl-lightness 0.4 | pastel lighten 0.32 | pastel format hex)"

  C01="$(pastel mix ${UNO} crimson       -f 0.5 | pastel mix - deeppink          -f 0.6 | pastel saturate 0.08 | pastel format hex)"
  C02="$(pastel mix ${UNO} darkseagreen  -f 0.5 | pastel mix - mediumspringgreen -f 0.6 | pastel saturate 0.08 | pastel format hex)"
  C03="$(pastel mix ${UNO} orange        -f 0.5 | pastel mix - coral             -f 0.6 | pastel saturate 0.08 | pastel format hex)"
  C04="$(pastel mix ${UNO} blue          -f 0.5 | pastel mix - deepskyblue       -f 0.6 | pastel saturate 0.04 | pastel format hex)"
  C05="$(pastel mix ${UNO} indigo        -f 0.5 | pastel mix - slateblue         -f 0.6 | pastel saturate 0.04 | pastel format hex)"
  C06="$(pastel mix ${UNO} darkturquoise -f 0.5 | pastel mix - deepskyblue       -f 0.6 | pastel saturate 0.08 | pastel format hex)"

  C09="$(pastel lighten 0.10 "$C01" | pastel format hex)"
  C10="$(pastel lighten 0.10 "$C02" | pastel format hex)"
  C11="$(pastel lighten 0.10 "$C03" | pastel format hex)"
  C12="$(pastel lighten 0.10 "$C04" | pastel format hex)"
  C13="$(pastel lighten 0.10 "$C05" | pastel format hex)"
  C14="$(pastel lighten 0.10 "$C06" | pastel format hex)"

  for x in "${MX_CC[@]}"; do export $x; done
}

demo () {
  for i in "${!MX_CC[@]}"; do
    local x=${MX_CC[i]}
    (( i == 2 )) && echo
    ! (( i % 2 )) && echo
    local textcolor=$(pastel textcolor ${!x} | pastel format hex)
    printf '\t'
    pastel paint "${textcolor}" -n -o "${!x}" "$x ${!x}"
  done
  echo
}

save () {
  for file in ./templates/*; do
    local out="./out/$(basename $file)"
    envsubst < "$file" | tee $out &> /dev/null
    echo " ::> $out"
  done
}

main () {
  generate_seed
  generate_palette
  save
  demo
}

{
  case ${1:-vivid} in
    --strategy) shift; STRATEGY=$1; shift;;
  esac
  main
}

  # for i in {09..14}; do
  #   local c="C0$(echo "$i - 8" | bc)"; c="${!c}"
  #   declare -g "C$i=$(pastel lighten   0.10 "$c" | pastel format hex)"
  # done

  # for i in 00 07 08 15; do
  #   local c="C$i"; local x="$i"
  #   [[ $i == 07 ]] && x=4
  #   local expo="0$(echo "scale=2; e(sqrt($x))/100" | bc -l)"
  #   declare -g "$c=$(pastel set hsl-saturation 0.16 "${UNO}" | pastel set hsl-lightness 0.06 | pastel lighten $expo | pastel format hex)"
  # done

